/**
 * ColdGameZone - Comprehensive 29-Game Master Registry
 * Pure client-side data with categorization, tags, ratings, and controls.
 */
const GAMES_DATA = [
    {
        id: "turbo",
        title: "Turbo Drive",
        subtitle: "Highway Fury",
        category: "racing",
        genre: "Top-Down Racer",
        rating: 4.9,
        badge: "FEATURED",
        plays: "68.4K",
        icon: "🏎️",
        accentColor: "#00f0ff",
        path: "game/index.html",
        desc: "High-octane highway traffic weaving with 3 selectable cars, dynamic nitro boost bursts, unlimited rocket launchers, and synthesized engine rumble.",
        controls: "WASD / Arrows to Steer & Accelerate • Shift for Nitro • Space / F to Fire Rockets • Touch D-pad & Buttons on Mobile",
        tags: ["racing", "cars", "turbo", "action", "retro", "arcade", "speed"]
    },
    {
        id: "fighter",
        title: "Cyber Brawler",
        subtitle: "Neon Clash",
        category: "action",
        genre: "2D Fighting Game",
        rating: 5.0,
        badge: "HOT",
        plays: "54.2K",
        icon: "🥊",
        accentColor: "#ff0055",
        path: "fighter/index.html",
        desc: "Competitive 2D arcade martial arts fighting game. Best 2 of 3 rounds featuring High Punches, Low Sweeping Kicks, Plasma Fireballs, 80% Guard Blocking, and lethal chip-out K.O. detection.",
        controls: "A/D Move • W Jump • J/Z Punch • K/X Kick • L/C Fireball • Hold Back to Guard Block • Full Touch Buttons",
        tags: ["action", "fighting", "fighter", "brawler", "combat", "versus", "pvp", "martial arts"]
    },
    {
        id: "stealth",
        title: "Ghost Protocol",
        subtitle: "Facility Infiltrator",
        category: "action",
        genre: "Top-Down Stealth",
        rating: 4.9,
        badge: "NEW",
        plays: "38.7K",
        icon: "🕵️",
        accentColor: "#00f0ff",
        path: "stealth/index.html",
        desc: "Infiltrate high-security Arasaka vaults using dynamic 2D raycasted vision cones, patrolling cyborg sentries, silent takedowns from behind, terminal hacking, and blinking laser tripwire evasion.",
        controls: "WASD / Arrows to Move • Shift to Sprint (Noisy!) • C to Crouch (Stealthy) • Space / F for Takedown • Touch D-pad & Action buttons",
        tags: ["stealth", "action", "infiltrator", "hack", "espionage", "tactical"]
    },
    {
        id: "bomber",
        title: "Cyber Bomber",
        subtitle: "Grid Detonator",
        category: "arcade",
        genre: "Tactical Arena Bomber",
        rating: 4.8,
        badge: "POPULAR",
        plays: "49.1K",
        icon: "💣",
        accentColor: "#ffaa00",
        path: "bomber/index.html",
        desc: "Classic Bomberman grid battle reimagined with 4-way cross blast flame propagation, chain reactions, destructible cyber-crates, powerup drops (+Bombs, +Fire, +Speed), and 3 adaptive bot cyborgs.",
        controls: "WASD / Arrows to Move • Space / Enter to Drop Bomb • Touch D-pad & Bomb Button",
        tags: ["bomber", "arcade", "bomberman", "explosions", "battle", "arena", "retro"]
    },
    {
        id: "pacman",
        title: "Quantum Maze",
        subtitle: "Cyber Ghost Hunt",
        category: "arcade",
        genre: "Retro Maze Chase",
        rating: 4.9,
        badge: "CLASSIC",
        plays: "62.3K",
        icon: "👾",
        accentColor: "#ffea00",
        path: "pacman/index.html",
        desc: "Classic maze arcade navigation featuring responsive direction input buffering, horizontal warp tunnels, 4 distinct AI ghost personalities (Blinky, Pinky, Inky, Clyde), and Quantum Energizers for ghost eating multipliers.",
        controls: "WASD / Arrows to Steer • Touch D-pad on mobile",
        tags: ["pacman", "arcade", "maze", "ghosts", "classic", "retro", "chomp"]
    },
    {
        id: "tycoon",
        title: "Cyber City Tycoon",
        subtitle: "Power Grid Builder",
        category: "strategy",
        genre: "City & Grid Simulation",
        rating: 4.8,
        badge: "DEEP",
        plays: "34.6K",
        icon: "⚡",
        accentColor: "#39ff14",
        path: "tycoon/index.html",
        desc: "Deep cyberpunk metropolis simulation. Balance daylight solar generation, continuous fusion cores, battery banks, power conduit networks, citizen satisfaction, and tax collection across a 12x9 sector grid.",
        controls: "Click / Tap toolbar to select structure • Click sector to build or demolish • Space to restart",
        tags: ["strategy", "tycoon", "simulation", "city", "power", "grid", "management"]
    },
    {
        id: "tetris",
        title: "Quantum Fall",
        subtitle: "Cyber Blocks",
        category: "puzzle",
        genre: "Falling Block Puzzle",
        rating: 5.0,
        badge: "TOP RATED",
        plays: "71.9K",
        icon: "🧱",
        accentColor: "#a855f7",
        path: "tetris/index.html",
        desc: "Authentic competitive falling block puzzle featuring standard 7-bag randomizer, Super Rotation System (SRS) with wall kicks, Ghost Piece projection, Hold slot, soft & hard drops, and 4-line TETRIS! multipliers.",
        controls: "Left/Right Move • Up/X Rotate CW • Z Rotate CCW • Down Soft Drop • Space Hard Drop • C/Shift Hold • Mobile touch controls",
        tags: ["tetris", "puzzle", "blocks", "falling", "retro", "arcade", "logic"]
    },
    {
        id: "billiards",
        title: "Neon Pool",
        subtitle: "Cyber Cue",
        category: "arcade",
        genre: "2D Physics Billiards",
        rating: 4.9,
        badge: "NEW",
        plays: "41.0K",
        icon: "🎱",
        accentColor: "#059669",
        path: "billiards/index.html",
        desc: "Precision 9-ball pool with sub-stepped 4x physics, elastic impulse collisions, cushion reflections with spin friction, cue drag power regulation, and standard 9-ball tournament rules.",
        controls: "Click / Touch on cue ball & drag backward to aim and set power • Release to shoot",
        tags: ["pool", "billiards", "physics", "sports", "cue", "arcade", "8ball"]
    },
    {
        id: "tactics",
        title: "Mech Warfare",
        subtitle: "Cyber Tactics",
        category: "strategy",
        genre: "Turn-Based Tactics",
        rating: 4.9,
        badge: "HOT",
        plays: "36.2K",
        icon: "🤖",
        accentColor: "#4f46e5",
        path: "tactics/index.html",
        desc: "Turn-based tactical mech combat on an 8x8 isometric grid. Command Vanguard Titan, Plasma Artillery, and Recon Scout against enemy cyborg swarms with telegraphed enemy intents and city pylon defense.",
        controls: "Click mech to select • Click green tile to move • Click red target to attack • Space / End Turn button",
        tags: ["tactics", "strategy", "mechs", "turnbased", "scifi", "combat", "grid"]
    },
    {
        id: "mining",
        title: "Deep Core",
        subtitle: "Nano Drill",
        category: "adventure",
        genre: "Subterranean Mining",
        rating: 4.8,
        badge: "POPULAR",
        plays: "44.8K",
        icon: "⛏️",
        accentColor: "#d97706",
        path: "mining/index.html",
        desc: "Descend into subterranean planetary strata with your nano drill pod. Mine 5 valuable ore tiers, manage fuel and cargo capacity, surface at the refinery to cash in, and upgrade your pod at the workshop.",
        controls: "WASD / Arrows to Drill & Fly • E to Sell / Upgrade at Surface • Touch D-pad & Buttons",
        tags: ["mining", "adventure", "upgrades", "drill", "subterranean", "crafting"]
    },
    {
        id: "golf",
        title: "Quantum Golf",
        subtitle: "Cyber Greens",
        category: "adventure",
        genre: "Physics Mini-Golf",
        rating: 4.8,
        badge: "NEW",
        plays: "32.1K",
        icon: "⛳",
        accentColor: "#10b981",
        path: "golf/index.html",
        desc: "Championship 9-hole mini-golf across cybernetic courses featuring quantum wormholes, speed booster acceleration strips, gravity vortices, stroke counters, and par scorecard tracking.",
        controls: "Click / Touch ball and drag backward to aim and power stroke • Release to putt",
        tags: ["golf", "minigolf", "physics", "sports", "holes", "casual", "putting"]
    },
    {
        id: "survivor",
        title: "Cyber Survivor",
        subtitle: "Neural Surge",
        category: "action",
        genre: "Bullet Heaven Roguelite",
        rating: 4.9,
        badge: "TOP RATED",
        plays: "65.7K",
        icon: "🧬",
        accentColor: "#ff0055",
        path: "survivor/index.html",
        desc: "Auto-firing Gatling cannons and orbital plasma drones versus overwhelming cyborg swarm waves. Collect XP crystals, choose dynamic perks on level-up, and defeat massive Omega Titan bosses.",
        controls: "WASD / Arrows to Move • Space / Enter to confirm upgrades • Touch controls on mobile",
        tags: ["action", "roguelite", "survivor", "swarm", "vampire", "auto-shooter", "bullet-hell"]
    },
    {
        id: "portal",
        title: "Quantum Portal",
        subtitle: "Aperture Shift",
        category: "puzzle",
        genre: "Physics Momentum Puzzle",
        rating: 4.9,
        badge: "FEATURED",
        plays: "58.3K",
        icon: "🌀",
        accentColor: "#00f0ff",
        path: "portal/index.html",
        desc: "Place Blue and Orange portals on conductive surfaces. Fling storage cubes through portals to preserve kinetic momentum, trigger pressure plates, disable laser grids, and escape test chambers.",
        controls: "A/D Move • W Jump • Left Click / Z Blue Portal • Right Click / X Orange Portal • E Grab Cube",
        tags: ["puzzle", "portal", "physics", "momentum", "brain", "scifi", "chamber"]
    },
    {
        id: "rogue",
        title: "Neon Rogue",
        subtitle: "Cyber Dungeon",
        category: "adventure",
        genre: "Action Dungeon Crawler",
        rating: 4.9,
        badge: "HOT",
        plays: "52.4K",
        icon: "🗡️",
        accentColor: "#ec4899",
        path: "rogue/index.html",
        desc: "Top-down dungeon crawler. Swap between Energy Katana and Cyber Shotgun, execute invulnerable dash-rolls through bullet hell patterns, clear procedural chambers, and defeat the Cyber Lich.",
        controls: "WASD Move • Mouse Aim & Click to Attack • Space Dash Roll • Q Swap Weapon",
        tags: ["rogue", "dungeon", "crawler", "action", "katana", "shotgun", "boss"]
    },
    {
        id: "tower",
        title: "Matrix Defense",
        subtitle: "Core Command",
        category: "strategy",
        genre: "Grid Tower Defense",
        rating: 4.8,
        badge: "POPULAR",
        plays: "47.2K",
        icon: "🏰",
        accentColor: "#3b82f6",
        path: "tower/index.html",
        desc: "Protect the central power core by placing and upgrading Pulse Blasters, Cryo Freezers, Tesla Arc chain lightnings, and armor-piercing Railguns across tactical waypoints.",
        controls: "Click tower card to select • Click grid cell to place • Click existing tower to upgrade or sell",
        tags: ["strategy", "tower-defense", "defense", "grid", "waves", "tactics", "upgrade"]
    },
    {
        id: "kart",
        title: "Cyber Drift",
        subtitle: "Neon Velocity",
        category: "racing",
        genre: "Pseudo-3D Curved Racer",
        rating: 4.9,
        badge: "FEATURED",
        plays: "59.6K",
        icon: "🏎️",
        accentColor: "#ff0055",
        path: "kart/index.html",
        desc: "Retro Mode-7 style curved road racing with 3-tier power drift boost sparks, 5 aggressive AI rival racers, and battlefield weapon items (EMP shockwaves, homing drones, nitro boosts).",
        controls: "WASD / Arrows to Steer & Accelerate • Shift / Space to Power Drift • F to Fire Item",
        tags: ["racing", "kart", "drift", "outrun", "pseudo3d", "speed", "multiplayer"]
    },
    {
        id: "match",
        title: "Neon Alchemist",
        subtitle: "Spell Matrix",
        category: "puzzle",
        genre: "Match-3 RPG Combat",
        rating: 4.8,
        badge: "POPULAR",
        plays: "43.1K",
        icon: "✨",
        accentColor: "#8b5cf6",
        path: "match/index.html",
        desc: "Match-3 puzzle combat. Align attack, mana, healing, and skull gems to build combo cascades and cast active spells (Flame Lance, Aegis Ward, Chrono Lock) against real-time boss turn attacks.",
        controls: "Click / Drag adjacent gems to swap • Click spell buttons when charged with mana",
        tags: ["puzzle", "match3", "rpg", "spells", "gems", "combat", "alchemist"]
    },
    {
        id: "pinball",
        title: "Quantum Pinball",
        subtitle: "Cyber Table",
        category: "arcade",
        genre: "Physics Arcade Pinball",
        rating: 4.8,
        badge: "CLASSIC",
        plays: "39.5K",
        icon: "⚡",
        accentColor: "#eab308",
        path: "pinball/index.html",
        desc: "Authentic physics pinball simulation featuring dual flippers, spring plunger, 3 reactive pop bumpers, drop targets, bonus score multiplier ladder, and 3-ball Multiball chaos.",
        controls: "Z / Left Arrow Left Flipper • / or Right Arrow Right Flipper • Down Arrow Plunger • Space Nudge",
        tags: ["pinball", "arcade", "physics", "flippers", "retro", "multiball", "table"]
    },
    {
        id: "shinobi",
        title: "Neon Shinobi",
        subtitle: "Shadow Blades",
        category: "action",
        genre: "Action Precision Slasher",
        rating: 4.9,
        badge: "TOP RATED",
        plays: "51.8K",
        icon: "⚔️",
        accentColor: "#06b6d4",
        path: "shinobi/index.html",
        desc: "Lightning-fast ninja action. Double jumps, wall kicks, and an invincible air dash. Deflect incoming enemy bullets back at foes with precision katana strikes and defeat the Cyber Daimyo.",
        controls: "A/D Move • W Jump (Double Jump & Wall Jump) • J/Z Katana Slash / Bullet Deflect • K/X Air Dash",
        tags: ["action", "ninja", "katana", "parry", "platformer", "slasher", "combat"]
    },
    {
        id: "deck",
        title: "Cyber Deck",
        subtitle: "Netrunner Duel",
        category: "strategy",
        genre: "Roguelike Deckbuilder",
        rating: 4.9,
        badge: "DEEP",
        plays: "42.9K",
        icon: "🃏",
        accentColor: "#3b82f6",
        path: "deck/index.html",
        desc: "Tactical card battles with a 3-energy economy. Read telegraphed enemy ICE intents, balance offensive malware exploits with defense firewalls, and draft new software programs into your deck.",
        controls: "Click card to select & click target/board to play • Click End Turn when finished",
        tags: ["strategy", "deckbuilder", "cards", "roguelike", "cyberdeck", "netrunner", "spire"]
    },
    {
        id: "flight",
        title: "Aero Striker",
        subtitle: "Sky Ace",
        category: "action",
        genre: "2.5D Rail Flight Combat",
        rating: 4.9,
        badge: "FEATURED",
        plays: "48.0K",
        icon: "✈️",
        accentColor: "#f43f5e",
        path: "flight/index.html",
        desc: "3D-perspective rail flight combat. Steer your starfighter across the screen, lock onto multiple drone targets with homing photon torpedoes, execute 360° defensive barrel rolls, and destroy the Valravn Dreadnought.",
        controls: "Mouse / WASD Flight Steer • Click / Space Twin Lasers • Hold Right Click Multi-Lock Torpedoes • Double tap A/D Barrel Roll",
        tags: ["action", "flight", "starfox", "rail-shooter", "space", "combat", "boss"]
    },
    {
        id: "puzzle",
        title: "Cyber Circuit",
        subtitle: "Logic Connect",
        category: "puzzle",
        genre: "Logic Puzzle",
        rating: 4.8,
        badge: "POPULAR",
        plays: "37.5K",
        icon: "🧩",
        accentColor: "#00f0ff",
        path: "puzzle/index.html",
        desc: "Connect pairs of matching neon terminals without crossing wire paths. Features 30 handcrafted levels with increasing grid complexity plus an infinite algorithmic puzzle generator.",
        controls: "Click / Drag mouse or finger between matching colored nodes to link circuits",
        tags: ["puzzle", "logic", "connect", "circuits", "flow", "brain", "neon"]
    },
    {
        id: "breaker",
        title: "Neon Breaker",
        subtitle: "Arkanoid Cyber Grid",
        category: "arcade",
        genre: "Breakout / Brick Breaker",
        rating: 4.7,
        badge: "CLASSIC",
        plays: "45.2K",
        icon: "🧱",
        accentColor: "#ff0055",
        path: "breaker/index.html",
        desc: "Shatter high-density neon brick formations with realistic angle deflections, multi-ball split powerups, paddle laser cannons, and explosive brick cascades.",
        controls: "Mouse / Touch or Left/Right Arrow keys to position paddle • Space to launch ball",
        tags: ["arcade", "breakout", "arkanoid", "bricks", "paddle", "classic", "retro"]
    },
    {
        id: "strike",
        title: "Cyber Strike",
        subtitle: "Space Bullet Hell",
        category: "action",
        genre: "Vertical Shmup",
        rating: 4.8,
        badge: "POPULAR",
        plays: "53.1K",
        icon: "🚀",
        accentColor: "#ff0055",
        path: "strike/index.html",
        desc: "Classic vertical scrolling space shmup. Weave through hypnotic bullet patterns, collect 5 weapon upgrade levels (spread shot, plasma laser, homing missiles), and deploy full-screen EMP bombs.",
        controls: "Mouse / Arrow keys to move ship • Auto-fire enabled • Space / B to trigger EMP bomb",
        tags: ["action", "shmup", "bullet-hell", "space", "shooter", "retro", "arcade"]
    },
    {
        id: "snake",
        title: "Neon Snake",
        subtitle: "Cyber Serpent",
        category: "arcade",
        genre: "Retro Arcade",
        rating: 4.7,
        badge: "CLASSIC",
        plays: "61.0K",
        icon: "🐍",
        accentColor: "#39ff14",
        path: "snake/index.html",
        desc: "Classic snake gameplay elevated with neon vector visuals, speed multiplier powerups, ghost wall-phasing mode, and smooth grid collision handling.",
        controls: "WASD / Arrow Keys or Swipe on Touchscreen to change direction",
        tags: ["arcade", "snake", "classic", "retro", "casual", "food", "high-score"]
    },
    {
        id: "jump",
        title: "Quantum Jump",
        subtitle: "Infinite Platformer",
        category: "adventure",
        genre: "Vertical Platformer",
        rating: 4.8,
        badge: "POPULAR",
        plays: "46.3K",
        icon: "🦘",
        accentColor: "#00f0ff",
        path: "jump/index.html",
        desc: "Doodle-jump style infinite vertical ascent. Navigate moving neon platforms, spring coils for massive leap boosts, crumbling platforms, and horizontal screen wrap-around.",
        controls: "A/D or Left/Right Arrow keys to steer • Tilt / Touch controls on mobile",
        tags: ["adventure", "platformer", "jump", "infinite", "arcade", "spring", "casual"]
    },
    {
        id: "pulse",
        title: "Cyber Pulse",
        subtitle: "Rhythm Synapse",
        category: "adventure",
        genre: "Rhythm Music Tap",
        rating: 4.8,
        badge: "HOT",
        plays: "40.9K",
        icon: "🎵",
        accentColor: "#ec4899",
        path: "pulse/index.html",
        desc: "Fast-paced 4-lane rhythm action game with synchronized procedural synthwave audio. Hit descending notes on the beat line to chain combo multipliers and reach SSS rank.",
        controls: "D, F, J, K keys or Touch the 4 lane buttons when notes cross the target bar",
        tags: ["rhythm", "music", "tap", "synthwave", "beats", "audio", "arcade"]
    },
    {
        id: "runner",
        title: "Gravity Runner",
        subtitle: "Inversion Shift",
        category: "racing",
        genre: "Endless Runner",
        rating: 4.8,
        badge: "POPULAR",
        plays: "49.8K",
        icon: "⚡",
        accentColor: "#ffea00",
        path: "runner/index.html",
        desc: "High-speed endless running with instantaneous gravity inversion. Flip between floor and ceiling to dodge laser barriers, spikes, and gap hazards while speed continuously scales.",
        controls: "Space / Click / Touch to invert gravity • Collect neon shards for shields",
        tags: ["runner", "gravity", "speed", "endless", "reflex", "racing", "arcade"]
    },
    {
        id: "defense",
        title: "Neon Defense",
        subtitle: "Orbital Command",
        category: "action",
        genre: "360° Turret Defense",
        rating: 4.7,
        badge: "POPULAR",
        plays: "35.4K",
        icon: "🛡️",
        accentColor: "#00f0ff",
        path: "defense/index.html",
        desc: "360-degree orbital defense. Rotate your shield and turret to intercept incoming missile swarms from all directions, deploy energy blasts, and safeguard the planet core.",
        controls: "Mouse cursor / Touch to rotate shield & aim • Click to shoot • Space for EMP",
        tags: ["defense", "action", "turret", "orbital", "arcade", "missiles", "shield"]
    }
];

// Helper to get game by ID
function getGameById(id) {
    return GAMES_DATA.find(g => g.id === id) || null;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { GAMES_DATA, getGameById };
}
